<?
    $items = $this->driver->getItems();
    $dbLabel = $this->driver->getDbLabel();
    $thumb = $this->driver->getThumbnail('medium');
    $pubType = $this->driver->getPubType();
    $accessLevel = $this->driver->getAccessLevel();
    $customLinks = $this->driver->getCustomLinks();
?>

<div class="span-5">
  <ul class="external-links ebsco">
    <? $pLink = $this->driver->getPLink();
    	if($pLink): ?>
      <li>
        <a href="<?=$pLink?>">
          <?=$this->transEsc('View in EDS')?>
        </a>
      </li>
    <? endif; ?>
    <? $pdfLink = $this->driver->getPdfLink();
    	if ($pdfLink): ?>
      <li>
        <a href="<?=$pdfLink?>" class="icon pdf fulltext">
          <?=$this->transEsc('pdf_full_text')?>
        </a>
      </li>
    <? endif; ?>
    <? if ($this->driver->getHTMLFullTextAvailability()): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->driver, 'fulltext')?>#html" class="icon html fulltext">
          <?=$this->transEsc('html_full_text')?>
        </a>
      </li>
    <? endif; ?>
    <? if (!empty($customLinks)): ?>
      <li>
        <ul class="custom-links">
          <? foreach ($customLinks as $customLink): ?>
        <? $url = isset($customLink['Url']) ? $customLink['Url'] : ''; 
        	$mot = isset($customLink['MouseOverText'])? $customLink['MouseOverText'] : '';
        	$icon = isset ($customLink['Icon']) ? $customLink['Icon'] : ''; 
        	$name = isset($customLink['Name']) ? $customLink['Name'] : '';?>
        <li>
          <a href="<?=$url?>" target="_blank" title="<?=$mot?>" class="custom-link">
            <? if ($icon): ?><img src="<?=$icon?>" /><? endif; ?><?=$name?>
          </a>
        </li>
          <? endforeach; ?>
        </ul>
      </li>
    <? endif; ?>
  </ul>
</div>

<div class="span-13">
  <h1>
    <?=$this->driver->getTitle()?>
  </h1>

  <table cellpadding="2" cellspacing="0" border="0" class="citation" summary="<?=$this->transEsc('Bibliographic Details')?>">
    <? foreach ($items as $key => $item): ?>
      <? if (!empty($item['Data'])): ?>
      <tr valign="top">
        <th width="150"><?=$this->transEsc($item['Label'])?>:</th>
        <td><?=$this->driver->linkUrls($item['Data'])?></td>
      </tr>
      <? endif; ?>
    <? endforeach; ?>

    <? if ($dbLabel): ?>
      <tr valign="top">
        <th width="150"><?=$this->transEsc('Database')?>:</th>
        <td><?=$this->escapeHtml($dbLabel)?></td>
      </tr>
    <? endif; ?>

    <? $fullText = $this->driver->getHtmlFullText();
    	if ($fullText): ?>
      <tr id="html" valign="top">
        <td colspan="2" style="padding:10px 0; border: 0">
          <?=$fullText?>
        </td>
      </tr>
    <? elseif ($accessLevel && !$this->account->isLoggedIn()): ?>
      <tr id="html" valign="top">
        <td colspan="2" style="padding:10px 0; border: 0">
          <p>
          	<a class="login" href="<?=$this->url('myresearch-home')?>"><strong><?=$this->transEsc('login_for_full_access')?></strong></a>
    		<?=$this->transEsc('fulltext_not_for_guests')?>
            <br />
            <strong><?=sprintf($this->transEsc('login_for_full_access'), $link)?></strong>
          </p>
        </td>
      </tr>
    <? endif; ?>
  </table>
</div>

<div class="span-4 last">
  <? if ($thumb): ?>
    <img src="<?=$this->escapeHtml($thumb)?>" class="summcover" alt="<?=$this->transEsc('book_jacket')?>"/>
  <? endif; ?>
  <? if ($pubType): ?>
    <p><?=$this->escapeHtml($pubType)?></p>
  <? endif; ?>
</div>

<div class="clear"></div>
