<? if (!empty($this->facetList)): ?>
  <h3><?=$this->transEsc('Limit To')?></h3>
  <? foreach ($this->facetList as $field => $facet): ?>
  <div class="span-5">
    <label class="displayBlock" for="limit_<?=$this->escapeHtml(str_replace(' ', '+', $field))?>"><?=$this->transEsc($facet['Label'])?>:</label>
    <? switch($facet['Type']){
		case 'multiselectvalue': ?>
    	<select id="limit_<?=$this->escapeHtml($field)?>" name="filter[]" multiple="multiple" size="10">
			<? foreach ($facet['LimiterValues'] as $id => $facetValue): ?>
        		<? $value = $facetValue['Value']; ?>
        		<option value="LIMIT|<?= $this->escapeHtml($field . ':' . $facetValue['Value'])?>"<?=(isset($favetValue['selected']) && $facetValue['selected'])?' selected="selected"':''?>><?=$this->escapeHtml($facetValue['Value'])?></option>
      		<? endforeach; ?>
    	</select>
    	<? break; 
		case 'select': 
			$value = $facet['LimiterValues'][0]['Value'] ?>
			<input type="checkbox" <?=(isset($facet['selected']) && $facet['selected'])?'checked="checked"':''?> name="filter[]" value="LIMIT|<?= $this->escapeHtml($field . ':' . $value)?>">
		<? break;
		case 'text': 
			$value = $facet['LimiterValues'][0]['Value'] ?>
			<input type="text" size="4" maxlength="20" class="advancedLimiter" name="limiter[]" id="limit_<?=$this->escapeHtml($value)?>" value="<?=$this->escapeHtml($value)?>" />
    	<? break;
     	}; ?>
  </div>
  <? endforeach; ?>
  <div class="clear"></div>
<? endif; ?>
<?=$this->render('search/advanced/limit.phtml')?>
<? if (isset($this->dateRangeLimit)): ?>
  <? /* Load the publication date slider UI widget */ $this->headScript()->appendFile('pubdate_slider.js'); ?>
  <input type="hidden" name="daterange[]" value="publishDate"/>
  <fieldset class="publishDateLimit span-5" id="publishDate">
    <legend><?=$this->transEsc('adv_search_year')?></legend>
    <label for="publishDatefrom"><?=$this->transEsc('date_from')?>:</label>
    <input type="text" size="4" maxlength="4" class="yearbox" name="publishDatefrom" id="publishDatefrom" value="<?=$this->escapeHtml($this->dateRangeLimit[0])?>" />
    <label for="publishDateto"><?=$this->transEsc('date_to')?>:</label>
    <input type="text" size="4" maxlength="4" class="yearbox" name="publishDateto" id="publishDateto" value="<?=$this->escapeHtml($this->dateRangeLimit[1])?>" />
    <div id="publishDateSlider" class="dateSlider"></div>
  </fieldset>
<? endif; ?>
<div class="clear"></div>
