---
# This file contains search specifications used by the reserves module; for details
# on the workings of this file, see the comments in searchspecs.yaml.
#-----------------------------------------------------------------------------------

AllFields:
  DismaxFields:
    - course^400
    - instructor^400
    - department^200

Instructor:
  DismaxFields:
    - instructor^400

Course:
  DismaxFields:
    - course^400

Department:
  DismaxFields:
    - department^400
